version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0"
    #       memory: 384M
  
  db:
    image: postgres:alpine
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0"
    #       memory: 512M

volumes:
  postgres-db:

